import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppContextProvider from "@/components/AppContext"
import "../style/globals.css";
import "../style/Markdown.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body > <AppContextProvider>{children}</AppContextProvider></body>
    </html>
  );
}
